algoritmo "semnome"
// Função :
// Autor :
// Data : 29/03/2016
// Seção de Declarações
var
num: inteiro
resul: real
resul_da_media: real
cont: inteiro
inicio
// Seção de Comandos


para cont de 1 ate 5 faca

   escreval ("Digite um número qualquer")
   leia (num)
   resul <- resul + num
   resul_da_media <- resul / 5 num



fimpara
escreval("soma = ", resul )
escreval("media = ", resul_da_media )

fimalgoritmo
