algoritmo "semnome"
// Função :
// Autor :
// Data : 24/03/2016
// Seção de Declarações
var
num1: real

inicio
// Seção de Comandos
escreval("digite um número qualquer")
leia(num1)
se (num1 > 0) entao
   escreval ("este numero é positivo")

senao
   se(num1 < 0) entao
      escreval("este número é negativo")

   senao
      se(num1 = 0) entao
         escreval("este numero é neutro")

      fimse
   fimse
fimse
fimalgoritmo
