algoritmo "semnome"
// Função :
// Autor :
// Data : 21/03/2016
// Seção de Declarações 

// ------------------EXERCICIO 1-------------------------------
var
CELSIUS, NUM2, NUM3, NUM4, RESUL_F: REAL
inicio
ESCREVAL ("DIGITE GRAU CELSIUS:")
LEIA (CELSIUS)

RESUL_F <- (CELSIUS * 1.8) + 32
ESCREVAL ("RESULTADO DA CONVERSÃO EM FAHRENHEIT", RESUL_F)

// Seção de Comandos 
fimalgoritmo


