algoritmo "Exercício de repetição - Multiplicação"
// Função :
// Autor :
// Data : 28/03/2016
// Seção de Declarações
var
cont: inteiro
num: inteiro

inicio
// Seção de Comandos
escreval ("Tabuada de qualquer número usando o PARA")
escreval ("----------------------------------------")
escreval ("Digite um número")
leia(num)

para cont de 1 ate 10 passo 1 faca

   escreval (num, " x ", cont, " = ", (num * cont))


fimpara
fimalgoritmo
