algoritmo "Estruturas de repetição"
// Função : Estrutura de repetição (enquanto... faca... fimenquanto...)
// Autor :
// Data : 24/03/2016
// Seção de Declarações 
var
    nome: literal
    cont:inteiro
inicio
// Seção de Comandos 

enquanto cont <= 5    faca
 escreval("----------------")
 escreval("informe um nome:")
 leia(nome)
 escreval("nome digitado foi: ", nome)
 cont <- cont + 1

fimenquanto

escreval("Continu O CÓDIGO")
fimalgoritmo
